name: webext
version: 0.1.3
description: A package for developing browser extensions. Supports Chrome, Edge, and Firefox.
homepage: https://github.com/terrier989/webext
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: '>=1.1.7 <2.0.0'
  js: '>=0.6.1 <1.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.5